### ISSUE TITLE
How to use this Project?如何使用这个项目？ 

### ISSUE THREAD

**Issue by 0x002500** [DazeCake/McsmBot#1]
# Can you make a User Manual?请问能制作一个用户手册吗？I am very interested in this project.我对这个项目很感兴趣。But I can't find any User Msnusl for this project.但是我找不到任何这个项目的使用说明。

**Comment by DazeCake** [comment]
很遗憾，我不会再对这个项目做任何更新。若mcsm没有破坏性的api变动，你仍然可以根据mirai的编译方式使用它的部分功能或者迁移代码到你自己的项目中。
